spring:
  application:
    name: TacoCloud

  thymeleaf:
    cache: false

  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: tacocloud
    local-datacenter: datacenter1
    schema-action: create-if-not-exists
    username: tacocloud
    password: tacocloud

logging:
  level:
    com.datastax.oss.driver: INFO
